### ISSUE TITLE
SOAP extension in 7.2 and 7.3

### ISSUE THREAD

**Issue by tobiassjosten** [linuxjuggler/php-xdebug-alpine#2]
Thanks for a great image! I'm using it in a lot of projects and am loving it. However, I'm missing the SOAP extension in 7.2 and 7.3.

It's explicitly enabled in 7.1 but not the others. Why is that? Is there anything hindering it from being added on the two others? Can I try and add it and send you a PR? :)

**Comment by zaherg** [comment]
hey @tobiassjosten, and sorry for the late reply, since not everyone is using SOAP (I used it in a small project with PHP 7.1 that's why it is there), I thought that keeping it out of the image is better, my main goal is to keep the images as small as I can, but you can always create your own image and use mine as the base for your images.

**Comment by tobiassjosten** [comment]
Thanks for getting back to me! I understand that and, in the end, we opted to create our own images based on the official PHP ones and inspired by yours. :)

If anyone's interested: https://hub.docker.com/r/stimtech/builder-php
